package portalrh.com.portalRH.enums;

public enum Escolaridade {

    FUNDAMENTALCOMPLETO,
    FUNDAMENTALINCOMPLETO,
    MEDIOCOMPLETO,
    MEDIOINCOMPLETO,
    GRADUACAOCOMPLETO,
    GRADUACAOINCOMPLETO,
    POSCOMPLETO,
    POSINCOMPLETO

}
